import '../globals.css';
import Link from 'next/link';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'OptiBus',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const navRefs = [
    { name: 'Dashboard', link: '/dashboard' },
    { name: 'Carport', link: '/carport' },
    { name: 'Driver', link: '/driver' },
    { name: 'Payments', link: '/payments' },
    { name: 'Reservations', link: '/reservations' },
    { name: 'Feedback', link: '/feedback' }
  ];

  return (
    <main className="w-screen h-screen flex">
      <div className="flex flex-col gap-2 w-40 h-screen bg-black/10">
        {navRefs?.map((data, key) => {
          return (
            <Link
              key={key}
              href={data.link}
              className="w-40 h-12 p-2 rounded font-semibold bg-black/10 hover:bg-black/5"
            >
              {data.name}
            </Link>
          );
        })}
      </div>
      <div className="w-full h-full">{children}</div>
    </main>
  );
}
