import '@/styles/globals.css';
import { ThemeProvider } from '@/components/ui/theme-provider';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'OptiBus',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen w-screen overflow-x-hidden bg-background text-accent dark:text-primary flex flex-col items-center select-none">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="w-full h-full">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
